services:
  - type: web
    name: flixzone-apis
    env: docker
    dockerContext: .
    plan: free
    autoDeploy: false
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER_NAME
        sync: false
      - key: DB_USER_PASSWORD
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
